version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: solid_todo_signal
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
